modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="zxbfm"
version="1.0.0"
displayName="ZetingX Better Food Mod"
credits="no credits"
displayURL="https://youtube.com/c/ZetingX"
authors="ZetingX"
description='''
Better foods :)
'''

[[dependencies.zxbfm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




